---
- hosts: localhost
  gather_facts: false
  tasks:  
    - name: Activa planificacion
      uri:
        url: http://192.168.68.10/api/v2/schedules/1/      
        validate_certs: no
        method: PATCH
        user: "{{ awx_username }}"
        password: "{{ awx_password }}"
        status_code: 200
        body: 
          {
            "enabled": true
          }
        body_format: json
        follow_redirects: "all"
        force_basic_auth: true
      register: request
      
    - debug: msg="{{ request.json.enabled }}"
