---
- hosts: localhost
  gather_facts: false
  tasks:  
    - name: Desactiva planificacion
      uri:
        url: http://10.87.28.10:30665/api/v2/schedules/8/      
        validate_certs: no
        method: PATCH
        user: "{{ awx_username }}"
        password: "{{ awx_password }}"
        status_code: 200
        body: 
          {
            "enabled": false
          }
        body_format: json
        follow_redirects: "all"
        force_basic_auth: true
      register: request
      
    - debug: msg="{{ request.json.enabled }}"
