---
- name: Installing Apache MSI
  hosts: all
  tasks:
    - name: Descarga de MSI-Apache
      win_get_url:
        url: https://archive.apache.org/dist/httpd/binaries/win32/httpd-2.2.25-win32-x86-no_ssl.msi
        dest: C:\Users\Administrator\Desktop\httpd-2.2.25-win32-x86-no_ssl.msi

    - name: Instala MSI
      win_package:
        path: C:\Users\Administrator\Desktop\httpd-2.2.25-win32-x86-no_ssl.msi
        state: present
