---
- name: Reinicio de servicio X
  hosts: all
  tasks:
    - name: Parar servicio X
      win_service:
        name: Audiosrv
        state: stopped

    - name: Iniciar servicio X
      win_service:
        name: Audiosrv
        state: started
